### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by whitead** [matteoferla/Python_SmallWorld_API#2] opened 2022-12-23 21:46 UTC
Cool library! We refer to it in [molbloom](https://github.com/whitead/molbloom)

This basic example seems to fail:
```py
aspirin = 'O=C(C)Oc1ccccc1C(=O)O'
data = sw.search(aspirin, dist=5, db=sw.REAL_dataset)
```

**Comment by matteoferla** [comment] 2022-12-24 18:02
The [SmallWorld server](https://sw.docking.org/search.html) still has the issue that the search hangs before finishing. 
...And this applies to Aspirin too in Zinc-All. Unfortunately.As expected, in [Zinc](https://zinc.docking.org/substances/ZINC000000000053/) aspirin is present (ZINC53), but SmallWorld does not find it.

But this is a curious case...
The pharmacy down the road sells it making it an off-the-shelf compound in the most literal sense, it appears in [Enamine Store](https://enaminestore.com/catalog) as a make-on-demand building block, EN300-19606. But it does not appear in Enamine REAL, which harkens to a frequent argument point of whether caring about Lipinski in the exploration phase of FBDD makes any sense (my opinion is No).

I was sent the endpoints and a blessing for the Enamine Store so I might add that at some point.

**Comment by whitead** [comment] 2022-12-24 19:19
Thanks - I just took the example from README. If I do this with a molecule I know is available, I still get an error:

```py
from smallworld_api import SmallWorld
sw = SmallWorld()
mol = 'CCOC(=O)Cc1ccc(N)c(N)c1'
data = sw.search(mol, dist=5, db=sw.REAL_dataset)
```
outputs:

```
HTTPError: 400 Client Error:  for url: https://sw.docking.org/search/submit?smi=CCOC%28%3DO%29Cc1ccc%28N%29c%28N%29c1&db=REAL_Space_21Q3_All_2B_public.smi.anon&dist=5&tdn=6&rdn=6&rup=2&ldn=2&lup=2&maj=6&min=6&sub=6
```

@maomlab actually contributed a PR that had a retry strategy that worked out for SmallWorld. See [code here](https://github.com/whitead/molbloom/pull/2). We ended up removing the code because we felt it was redundant with your library.

**Comment by matteoferla** [comment] 2022-12-24 20:20
Ah. The database name is wrong in that particular error. The address of the Enamine Real and other DBs have expired since the last release. So `retrieve_databases` is required for an update. I will have to change this to happen automatically during init as it makes no sense like this. However, an old error is back afterwards:
```python
sw = SmallWorld()
dbs: pd.DataFrame = sw.retrieve_databases()
#sw.stream_response = True # | False no difference...
results : pd.DataFrame = sw.search(aspirin, dist=5, db=sw.REAL_dataset)
```

    ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

This blank line crash was present previously, but then disappeared and now is back. I will have to add a safeguard as the hit query id will have been given prior to the search crash, which can be retrieved even if it broke. I'll re-introduce this after Christmas 🤷

**Comment by whitead** [comment] 2022-12-24 20:46
Yea this is why I didn't want to have it in `molbloom` - it's a never-ending whackamol as vendors change URLs, policies, and formats. Thank you for your service on this. 🫡🫡🫡

**Comment by momeara** [comment] 2022-12-25 02:57
@jir322 Would it possible to have something like an `enamine-current` database that would be be kept up-to-date as new enamine catalogs come out?

**Comment by matteoferla** [comment] 2022-12-25 07:33
So I had another gander... and it turned out that in my quick check I had used an old version (...home laptop)... the chunking error had since been fixed. However, the need to update of the databases is an annoying thing so it is now done automatically during initialisation. As this is working, I am closing the issue.

However, the smallworld server is still glitchy and does not finishing checking everything, so the results are actually incomplete most times, but this is a problem outside this project.

**Closed as completed by matteoferla** 2022-12-25 07:33 UTC

**Comment by jir322** [comment] 2022-12-27 16:53
we updated Enamine Private 29B in December.
We are updating ZINC22 (37B) over the holidays. Should be ready Jan 3.
We get a new release every 6 months or so. We try to process quickly but
sometimes "events" get in the way.
We will try to be better in future.

John Irwin
UCSF Pharmaceutical Chemistry
http://irwinlab.compbio.ucsf.edu

**Comment by jir322** [comment] 2022-12-27 16:55
please describe exactly what you are seeing as a "glitch" so we can
reproduce and fix if we can.
perhaps file a separate thread.
We do have to make economies (e.g. 5 or 10 sec search time limit)  to make
the system pragmatic and open to all.
But we are open to your advice.

John Irwin
UCSF Pharmaceutical Chemistry
http://irwinlab.compbio.ucsf.edu

**Comment by matteoferla** [comment] 2023-01-03 10:43
@jir322 by glitch I mean the issue I emailed you about on the 14/11/22 wherein the searches are incomplete and the queried molecule is not found. `Cc1ccc(CNC(=O)C2CCC2)cn1` is `Z437516460` in Enamine REAL, but Smallworld does not find it. Aspirin (`CCOC(=O)Cc1ccc(N)c(N)c1`) is another odd case that is missing in some searches (albeit not part of all DBs being an acid).
In the first step of the query, the pooling stream, there are four outcomes for completed, ongoing, an app-internal communication issue ('Major Tom', which AFAIK is harmless) and the app raising a 404 response (stream chunking error). The latter is recent so I assume it has something to do with the missing compound in the results.

The issue this thread was raised was for my clientside Python API not updating the DBs names _automatically_, which it does now.
